# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8d8c54ba8740a1cde7b57d058233c693182671a2fc582f716987229509d83e15ac8801260452a97f54e15ed4950e2e4b66632bd3d424cd16bb39432a6c91246

test:
  secret_key_base: 36ca394a17b9d73ee75fa7681f5af608c504acee7692a345567bebdb0a90de727020686ce6c43e0d923e660f63d49917efb1d1c855faeff270fe24329287749e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
